from abc import ABC, abstractmethod
from typing import Any, TypeVar

from pydantic import BaseModel

T = TypeVar("T", bound=BaseModel)


class LLMPort(ABC):
    """Contract for any LLM provider (OpenAI, Anthropic, etc.)."""

    @abstractmethod
    async def complete(self, prompt: str, system: str) -> str:
        """Generate a text completion for a prompt.

        Args:
            prompt: User prompt sent to the model.
            system: System instructions that guide the model's behavior.

        Returns:
            Text generated by the model.
        """

    @abstractmethod
    async def complete_structured(self, prompt: str, schema: type[T], system: str = "") -> T:
        """Generate a completion validated against a Pydantic schema.

        Args:
            prompt: User prompt sent to the model.
            schema: Pydantic model used to validate the generated output.
            system: Optional system instructions that guide the model's behavior.

        Returns:
            Generated output validated as an instance of ``schema``.
        """

    @abstractmethod
    def as_runnable(self) -> Any:
        """Expose the underlying model as a LangChain runnable.

        Returns:
            Runnable model that can be bound to tools in LangGraph agents.
        """
